#!/bin/bash

set -e # exit on error
set -x # echo commands

# Install Miniconda3
if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
fi
bash miniconda.sh -b -p $HOME/miniconda

conda config --set always_yes yes --set changeps1 no
conda update conda
