#!/bin/bash

set -e # exit on error
set -x # echo commands

# Skip if not using continuous integration system
#
# We assume after this that either miniconda or Anaconda distribution
# is pre-installed

if [[ "$CONTINUOUS_INTEGRATION" = true ]]
then
    # Install Miniconda3
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    fi
    bash miniconda.sh -b -p $HOME/miniconda

    conda config --set always_yes yes --set changeps1 no
    conda update conda
fi
