#!/bin/bash

set -e # exit on error
set -x # echo commands

# Do the base install
bash scripts/ci/install

# Dependencies for testing/benchmarking
conda create -n test-environment python=$PYTHON_VERSION
source activate test-environment
conda install dask numba numpy pandas pillow toolz xarray datashape colorcet rasterio scikit-image param
conda install -c gbrener -c conda-forge xarray # remove this line when xarray >= 0.9.7
conda install -c conda-forge pytest pytest-benchmark
conda install flake8 matplotlib
python setup.py develop --no-deps
conda env export
