#!/bin/bash

set -e # exit on error
set -x # echo commands

# Do the base install
bash scripts/ci/install

# Dependencies for linting/verifying notebook examples
conda env create --file examples/environment.yml
source activate ds
conda remove datashader
python setup.py develop --no-deps
conda env export
