#!/bin/bash

set -e # exit on error
set -x # echo commands

# TODO: why different tests for python 2 vs 3?
source activate test-environment
if [[ $PYTHON_VERSION == '2.7' ]]
then
    py.test datashader/tests --doctest-modules --doctest-ignore-import-errors --verbose
else
    py.test datashader/tests --verbose
fi

flake8 --ignore E,W datashader examples
py.test datashader/benchmarks
