{% set sdata = load_setup_py_data(setup_file="../../../setup.py", from_recipe_dir=True) %}

package:
  name: {{ sdata['name'] }}
  version: {{ VERSION }}

source:
  url: ../../../dist/{{ sdata['name'] }}-{{ VERSION }}-py3-none-any.whl

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv {{ sdata['name'] }}-{{ VERSION }}-py3-none-any.whl
  entry_points:
    {% for group,epoints in sdata.get("entry_points",{}).items() %}
    {% for entry_point in epoints %}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - python {{ sdata['python_requires'] }}
    - param >=1.7.0
    - pyct-core >=0.4.4
    - setuptools >30.3.0
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata.get('install_requires',{}) %}
    - {{ dep if dep != 'dask' else 'dask-core'}}
    {% endfor %}
    # adding pyct here is temporary (this conda recipe template will disappear when new pyctdev is released)
    - pyct
  run_constrained:
    - cudf >=0.10.0
test:
  imports:
    - datashader

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
