package:
  name: datashader
  version: 0.6.0dev1

extra:
  channels:
    - numba

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dask >=0.7.6
    - datashape >=0.5.1
    - numba >=0.24.0
    - odo >=0.4.1
    - numpy >=1.7
    - pandas >=0.15.0
    - pillow >=3.1.1
    - xarray >=0.9.6
    - toolz >=0.7.4
    - colorcet >=0.9.0
    - param >=1.5.1,<2.0

test:
  requires:
    - pytest >=2.8.5
    - rasterio >=1.0

  imports:
    - datashader

about:
  home: https://github.com/bokeh/datashader
  license: New BSD
