package:
  name: datashader
  version: 0.6.2

extra:
  channels:
    - numba
    - gbrener
    - conda-forge

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dask >=0.15.4
    - datashape >=0.5.1
    - numba >=0.35.0
    - numpy >=1.7
    - pandas >=0.15.0
    - pillow >=3.1.1
    - xarray >=0.9.6
    - toolz >=0.7.4
    - colorcet >=0.9.0
    - param >=1.5.0,<2.0

test:
  requires:
    - pytest >=2.8.5
    - pytest-benchmark >=3.0.0
    - rasterio
    - scipy

  imports:
    - datashader

about:
  home: https://github.com/bokeh/datashader
  license: New BSD
