name: downstream_tests

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [packages]
    types: [completed]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  downstream_tests:
    name: Run downstream tests
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push') || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        downstream_repo: [holoviews, hvplot]
      fail-fast: false
    steps:
      - uses: holoviz-dev/holoviz_tasks/downstream-tests@17107a157b32cc1bd2a09c71fbdbc74603efdb40 # v1.0.15
        with:
          downstream_repo: ${{ matrix.downstream_repo }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
